### ISSUE TITLE
Add point for version control

### ISSUE THREAD

**Issue by vsoch** [vsoch/contributor-ci#19]
```yaml
CFA-version-control:
  description: Is the project version controlled?
  rationale: Version control allows for easy collaboration and preservation of changes over time
  criteria:
    - name: The project is on GitHub, GitLab, or another service that provides version control
```
